FROM registry.cn-zhangjiakou.aliyuncs.com/atguigu-k8s/jdk:jdk8 as builder
RUN curl -L https://dlcdn.apache.org/zookeeper/zookeeper-3.7.1/apache-zookeeper-3.7.1-bin.tar.gz | sudo tar -zx --no-same-owner && \
    sudo mv apache-zookeeper-3.7.1-bin /opt/module/zookeeper
COPY entrypoint.sh /opt/module/zookeeper/bin
RUN sudo chmod +x /opt/module/zookeeper/bin/entrypoint.sh && \
    sudo chown -R atguigu:atguigu /opt/module/zookeeper

FROM registry.cn-zhangjiakou.aliyuncs.com/atguigu-k8s/jdk:jdk8
COPY --from=builder --chown=atguigu:atguigu /opt/module/zookeeper /opt/module/zookeeper
ENV ZOOKEEPER_HOME=/opt/module/zookeeper
CMD [ "/opt/module/zookeeper/bin/entrypoint.sh" ]