FROM registry.cn-zhangjiakou.aliyuncs.com/atguigu-k8s/base-centos
USER atguigu
RUN curl -L https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u352b08.tar.gz | sudo tar -zx --no-same-owner && \
    sudo mv jdk8u352-b08 /opt/module/java

ENV JAVA_HOME=/opt/module/java
ENV PATH=$PATH:$JAVA_HOME/bin