name: Hadoop
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - JDK
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - hadoop/**
      - .github/workflows/hadoop.yaml

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: atguigu-k8s
  IMAGE: hadoop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Detect Date
        run: echo "VERSION=$(date +%F)" >>$GITHUB_ENV
      - name: Build JDK8
        run: |
          TAG=${VERSION}
          docker login \
            --username="${{ secrets.DOCKER_USERNAME }}" \
            --password="${{ secrets.DOCKER_PASSWORD }}" \
            ${REGISTRY}
          cd ${IMAGE}
          docker build . --file Dockerfile-jdk8 \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk8 \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk8-${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk8
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk8-${TAG}
      - name: Build JDK11
        run: |
          TAG=${VERSION}
          docker login \
            --username="${{ secrets.DOCKER_USERNAME }}" \
            --password="${{ secrets.DOCKER_PASSWORD }}" \
            ${REGISTRY}
          cd ${IMAGE}
          docker build . --file Dockerfile-jdk11 \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk11 \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk11-${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk11
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:jdk11-${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest